name: tests

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  run-tests:
    strategy:
      matrix:
        go: ['1.23', '1.24']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set Go Version 
        uses: actions/setup-go@v4
        with:
          go-version:  ${{ matrix.go }}

      - name: Setup RabbitMQ
        uses: nijel/rabbitmq-action@v1.0.0
        with:
          rabbitmq version: '5'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: go mod package cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('tests/go.mod') }}

      - name: Run Tests
        run: |
          chmod +x ./tests/.sh
          GITHUB_ACTION=true GORM_DIALECT=sqlite ./tests/.sh
